[package]
name = "codecrafters-shell"
version = "0.1.0"
authors = ["Codecrafters <hello@codecrafters.io>"]
edition = "2021"
rust-version = "1.80"

[dependencies]
anyhow = "1.0.68"                                         # error handling
bytes = "1.3.0"                                           # helps manage buffers
dirs = "6.0.0"
os_pipe = "1.2.2"
rustyline = { version = "17.0.2", features = ["derive"] }
shellwords = "1.1.0"
thiserror = "2.0.17"                                      # error handling
trie-rs = "0.4.2"
